{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sitmo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sitmo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sitmo/sitmo_{{ version }}.tar.gz
  sha256: 448ef8d56e36783354011845daf33f1efb83ea3b9685eea75eaf5134e24fa8c2

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-rcpp >=0.12.13
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - r-rcpp >=0.12.13

test:
  commands:
    - $R -e "library('sitmo')"           # [not win]
    - "\"%R%\" -e \"library('sitmo')\""  # [win]

about:
  home: https://thecoatlessprofessor.com/projects/sitmo/, https://github.com/stdfin/random/
  dev_url: https://github.com/coatless/sitmo
  license: MIT
  summary: Provided within are two high quality and fast PPRNGs that may be used in an 'OpenMP' parallel environment. In addition, there is a generator for one dimensional low-discrepancy sequence. The objective of this library to consolidate the distribution of the 'sitmo' (C++98 & C++11), 'threefry' and 'vandercorput'
    (C++11-only) engines on CRAN by enabling others to link to the header files inside of 'sitmo' instead of including a copy of each engine within their individual package. Lastly, the package contains example implementations using the 'sitmo' package and three accompanying vignette that provide additional information.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
